# Site settings
title: Shahana's Art
email: "www.shahanasana48@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  Drawings and artwork by Shahana Karippayi.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: ""
# github_username: ""

# Build settings
markdown: kramdown
permalink: none
