# Site settings
title: Shahana's Portfolio
email: "www.shahanasana48@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  Creative works by Shahana.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sana.shahidh.in" # the base hostname & protocol for your site
# twitter_username: ""
# github_username: ""

# Build settings
markdown: kramdown
permalink: none
